#!/usr/bin/env bash
# Start the antigravity bridge proxy on port 4003
# Runs inside wargames-dev container

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load secrets from .env if present (generated by: secrets inject wargames-dev)
if [[ -f "$SCRIPT_DIR/.env" ]]; then
    set -a; source "$SCRIPT_DIR/.env"; set +a
fi

# Required env vars — set via secrets inject or export manually
: "${ANTIGRAVITY_CLIENT_ID:?Set ANTIGRAVITY_CLIENT_ID (run: secrets inject wargames-dev)}"
: "${ANTIGRAVITY_CLIENT_SECRET:?Set ANTIGRAVITY_CLIENT_SECRET (run: secrets inject wargames-dev)}"

echo "Starting antigravity bridge on :4003..."
exec python "$SCRIPT_DIR/bridge.py"
